#!/usr/bin/env fish

read -P "ID: " id
read -P "Description: " description

if not test -d ./archives
    mkdir ./archives
end

set file "./archives/$(test -n "$description"; and printf "%s_%s.cpp" $id $description; or echo $id.cpp)"

while read -P "Problem: " -L problem
    if test -z "$problem"
        echo // >>$file
        continue
    end
    echo "// $problem" >>$file
end

echo >>$file
echo "// Sample Input" >>$file
for line in (cat ./src/in.txt)
    echo "// $line" >>$file
end

echo >>$file
echo "// Sample Output" >>$file
for line in (cat ./src/out.txt)
    echo "// $line" >>$file
end

if test -f ./src/__append__.cpp
    echo >>$file
    echo "// Append Code Start" >>$file
    for line in (cat ./src/__append__.cpp)
        echo $line >>$file
    end
    echo "// Append Code End" >>$file
end

echo >>$file
for line in (cat ./src/main.cpp)
    if not test $line = '#include "__append__.cpp"'
        echo $line >>$file
    end
end
