#!/usr/bin/env fish

argparse n/onlytouching y/yes -- $argv

if not set -q _flag_y
    echo "This will override your workspace."
    while read -n 2 -P "Are you sure? (y/N): " response
        or return 1
        switch $response
            case y Y
                break
            case n N ''
                return 1
            case *
                echo Not valid input
                continue
        end
    end
end

if not test -d ./src
    mkdir ./src
end

rm -f ./src/main.cpp
rm -f ./src/in.txt
rm -f ./src/out.txt

touch ./src/main.cpp ./src/in.txt ./src/out.txt

if not set -q _flag_n
    printf "#include <iostream>\nusing namespace std;\n\n" >>./src/main.cpp

    while read -P "Smaple Input: " -L smaple_input
        echo $smaple_input >>./src/in.txt
    end

    while read -P "Smaple Output: " -L smaple_output
        echo $smaple_output >>./src/out.txt
    end

    printf "int main() {\n\n  return 0;\n}" >>./src/main.cpp
end
